services:
  - type: web
    name: solicitudes-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: solicitudes-frontend
    runtime: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
